FROM jenkins/agent:latest

USER root

RUN apt-get update && apt-get install -y \
    npm \
    nodejs \
    docker.io \
    git \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g npm@latest

USER jenkins
